# Pre-commit hooks configuration for TaskFlow
# See https://pre-commit.com for more information

repos:
  # General formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

  # Python specific
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        files: ^(backend|ai-worker)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(backend|ai-worker)/.*\.py$
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^(backend|ai-worker)/.*\.py$
        args: ['--max-line-length=100', '--ignore=E203,W503']

# Configuration for specific tools
files: |
  (?x)^(
    backend/.*|
    ai-worker/.*|
    frontend/src/.*|
    database/.*|
    scripts/.*|
    .*\.(py|js|jsx|ts|tsx|sql|yaml|yml|json|md)$
  )$

exclude: |
  (?x)^(
    .*/(node_modules|venv|dist|build|coverage|htmlcov)/.*|
    .*/\.(git|pytest_cache|mypy_cache)/.*|
    .*\.(pyc|pyo|lock)$|
    frontend/package-lock\.json
  )$