# YAML linting configuration for TaskFlow

extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
    indent-sequences: true
  document-start: disable

ignore: |
  node_modules/
  .tox/
  *.egg-info/
  frontend/build/