#!/bin/bash

# Script to generate PostgreSQL init scripts ConfigMap from the init-complete.sql file

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SQL_FILE="$PROJECT_ROOT/database/postgresql/init-complete.sql"
OUTPUT_FILE="$PROJECT_ROOT/k8s/base/postgres-init-scripts-configmap.yaml"

if [ ! -f "$SQL_FILE" ]; then
    echo "Error: SQL file not found at $SQL_FILE"
    exit 1
fi

echo "Generating PostgreSQL init scripts ConfigMap..."

cat > "$OUTPUT_FILE" << 'EOF'
# PostgreSQL Init Scripts ConfigMap
# Auto-generated from database/postgresql/init-complete.sql
# DO NOT EDIT THIS FILE DIRECTLY - Edit the source SQL file and run scripts/generate-postgres-init-configmap.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: taskflow
  labels:
    app: postgres
    app.kubernetes.io/name: postgres-init-scripts
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: taskflow
data:
  01-init-complete.sql: |
EOF

# Append the SQL file content with proper indentation
sed 's/^/    /' "$SQL_FILE" >> "$OUTPUT_FILE"

echo "Successfully generated $OUTPUT_FILE"