# TaskFlow AI Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-ai
  namespace: taskflow
  labels:
    app: taskflow-ai
    app.kubernetes.io/name: taskflow-ai
    app.kubernetes.io/component: ai-worker
    app.kubernetes.io/part-of: taskflow
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1 # AI worker can be scaled horizontally
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: taskflow-ai
  template:
    metadata:
      labels:
        app: taskflow-ai
        app.kubernetes.io/name: taskflow-ai
        app.kubernetes.io/component: ai-worker
        app.kubernetes.io/part-of: taskflow
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ai-worker
          image: docker.io/jessiewbailey/taskflow-ai:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          envFrom:
            - secretRef:
                name: taskflow-env
          env:
            # Service Discovery - How AI worker references other services
            - name: BACKEND_API_URL
              value: "http://taskflow-api:8000" # Service name resolution
            # Ollama Host - configured via environment variable
            - name: OLLAMA_HOST
              value: "http://ollama-service:11434" # Points to Ollama service in same namespace
            # Qdrant Vector Database
            - name: QDRANT_URL
              value: "http://qdrant:6333"
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: taskflow-deployment-config
                  key: DEFAULT_MODEL
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 18 # 3 minutes total
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: taskflow-config
        - name: tmp
          emptyDir: {}
      restartPolicy: Always
