# TaskFlow Kustomization Configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for all resources
namespace: taskflow

# Common metadata applied to all resources
metadata:
  name: taskflow
  
labels:
  - pairs:
      app.kubernetes.io/name: taskflow
      app.kubernetes.io/part-of: taskflow
      app.kubernetes.io/version: "1.0.0"

# Resources to deploy
resources:
  # Namespaces are created manually via kubectl
  - qdrant-deployment.yaml     # Qdrant vector database for RAG search
  - ollama-deployment.yaml     # Ollama LLM server in llm namespace
  - redis-deployment.yaml      # Redis for event bus and pub/sub
  - secrets.yaml               # Actual secrets with real passwords
  - config-configmap.yaml      # Domain configuration
  - deployment-config.yaml     # Deployment configuration options
  # postgres-init-scripts-configmap.yaml replaced by configMapGenerator below
  - postgres-statefulset.yaml
  - api-deployment.yaml
  - ai-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - rbac-limited.yaml           # Service account permissions for logs (namespace-only)
  # - ingress.yaml create ingresses manually

# Container image management
images:
  - name: docker.io/jessiewbailey/taskflow-api
    newName: docker.io/jessiewbailey/taskflow-api
    newTag: latest
  - name: docker.io/jessiewbailey/taskflow-ai
    newName: docker.io/jessiewbailey/taskflow-ai
    newTag: latest  
  - name: docker.io/jessiewbailey/taskflow-web
    newName: docker.io/jessiewbailey/taskflow-web
    newTag: latest
  - name: docker.io/jessiewbailey/taskflow-ollama
    newName: docker.io/jessiewbailey/taskflow-ollama
    newTag: latest

# JSON/YAML patches (optional)
patches:
  - target:
      kind: Deployment
      name: taskflow-api
    path: api-deployment-patch.yaml

# Replicas override (for different environments)
# Uncomment and modify for different environments
# replicas:
#   - name: taskflow-api
#     count: 3
#   - name: taskflow-web
#     count: 3
#   - name: taskflow-ai
#     count: 2

# Resource transformations
transformers: []

# ConfigMap Generators
configMapGenerator:
  - name: taskflow-ui-labels
    files:
      - labels.yaml
    options:
      disableNameSuffixHash: true
  - name: postgres-init-scripts
    files:
      - 01-init-complete.sql
    options:
      disableNameSuffixHash: true
