apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base configuration
resources:
  # Namespaces are created manually via kubectl
  # longhorn-storageclass.yaml  # Longhorn creates its own StorageClass during installation
  - qdrant-deployment.yaml     # Qdrant vector database for RAG search
  - ollama-deployment.yaml     # Ollama LLM server in llm namespace
  - redis-deployment.yaml      # Redis for event bus and pub/sub
  - secrets.yaml               # Actual secrets with real passwords
  - config-configmap.yaml      # Domain configuration
  - deployment-config.yaml     # Deployment configuration options
  # postgres-init-scripts-configmap.yaml replaced by configMapGenerator below
  - postgres-statefulset.yaml
  - api-deployment.yaml
  - ai-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - rbac-limited.yaml           # Service account permissions for logs (namespace-only)
  # - ingress.yaml create ingresses manually

# Container image management

# ConfigMap generators
configMapGenerator:
  - name: taskflow-ui-labels
    files:
      - labels.yaml
    options:
      disableNameSuffixHash: true
  - name: postgres-init-scripts
    files:
      - 01-init-complete.sql
    options:

# Image transformations
images:
  - name: docker.io/jessiewbailey/taskflow-api
    newName: docker.io/jessiewbailey/taskflow-api
    newTag: latest
  - name: docker.io/jessiewbailey/taskflow-ai
    newName: docker.io/jessiewbailey/taskflow-ai
    newTag: latest
  - name: docker.io/jessiewbailey/taskflow-web
    newName: docker.io/jessiewbailey/taskflow-web
    newTag: latest
  - name: docker.io/jessiewbailey/taskflow-ollama
    newName: docker.io/jessiewbailey/taskflow-ollama
    newTag: latest

# Labels
labels:
  - pairs:
      app.kubernetes.io/name: taskflow
      app.kubernetes.io/part-of: taskflow
      app.kubernetes.io/version: "1.0.0"


# Namespace
namespace: taskflow
