apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  type: DirectoryOrCreate
