# UI Labels Configuration
# This file contains all text labels used in the TaskFlow application
# Modify these to customize the terminology for your specific use case

# Application branding
app:
  name: "TaskFlow"
  title: "Task Processing System"
  description: "Generic task processing and workflow management system"

# Main terminology
terminology:
  # Core entities
  task: "Task"
  tasks: "Tasks"
  request: "Request"
  requests: "Requests"
  requester: "Requester"
  analyst: "Analyst"
  processing: "Processing"
  workflow: "Workflow"
  workflows: "Workflows"
  
  # Actions
  new_task: "New Task"
  new_request: "New Request"
  submit: "Submit"
  process: "Process"
  review: "Review"
  analyze: "Analyze"
  complete: "Complete"
  assign: "Assign"
  
  # Status labels
  status:
    new: "New"
    in_review: "In Review"
    pending: "Pending"
    closed: "Closed"
    
  # Priority levels
  priority:
    low: "Low"
    medium: "Medium"
    high: "High"
    urgent: "Urgent"

# Dashboard labels
dashboard:
  title: "Dashboard"
  filters: "Filters"
  search_placeholder: "Search tasks..."
  no_tasks: "No tasks found"
  loading: "Loading..."
  
  # Table headers
  table:
    id: "ID"
    text: "Text"
    requester: "Submitter"  # Change this to customize the submitter column header
    status: "Status"
    analyst: "Assignee"     # Change this to customize the assignee column header
    created: "Created"
    due_date: "Due Date"
    priority: "Priority"
    date_submitted: "Date Submitted"
    processing_status: "Processing Status"
    
  # Action buttons
  actions:
    view: "View"
    edit: "Edit"
    delete: "Delete"
    assign: "Assign"
    logs: "Logs"
    settings: "Settings"

# Forms and modals
forms:
  new_task_modal:
    title: "Create New Task"
    task_text_label: "Task Description"
    task_text_placeholder: "Enter task description..."
    requester_label: "Submitter"  # Change this to customize the submitter field label
    requester_placeholder: "Enter submitter name or organization..."
    priority_label: "Priority"
    due_date_label: "Due Date"
    submit_button: "Create Task"
    cancel_button: "Cancel"
    
  filters:
    status_filter: "Filter by Status"
    analyst_filter: "Filter by Analyst"
    date_range: "Date Range"
    priority_filter: "Filter by Priority"
    clear_filters: "Clear Filters"
    
  # Drawer/sidebar
  drawer:
    task_details: "Task Details"
    ai_analysis: "AI Analysis"
    summary: "Summary"
    topic: "Topic"
    sensitivity: "Sensitivity Score"
    redactions: "Suggested Redactions"
    custom_instructions: "Custom Instructions"
    processing_log: "Processing Log"

# Settings page
settings:
  title: "Settings"
  workflow_settings: "Workflow Settings"
  ai_settings: "AI Settings"
  user_settings: "User Settings"
  system_settings: "System Settings"
  
  # Workflow configuration
  workflows:
    title: "Workflow Configuration"
    create_workflow: "Create Workflow"
    edit_workflow: "Edit Workflow"
    workflow_name: "Workflow Name"
    workflow_description: "Description"
    workflow_blocks: "Workflow Blocks"
    add_block: "Add Block"
    
  # AI configuration
  ai:
    title: "AI Configuration"
    model_settings: "Model Settings"
    prompt_templates: "Prompt Templates"
    custom_instructions: "Custom Instructions"

# Error messages
errors:
  generic: "An error occurred. Please try again."
  network: "Network error. Please check your connection."
  validation: "Please check your input and try again."
  permission: "You don't have permission to perform this action."
  not_found: "The requested item was not found."
  server_error: "Server error. Please try again later."

# Success messages
success:
  task_created: "Task created successfully"
  task_updated: "Task updated successfully"
  task_deleted: "Task deleted successfully"
  workflow_saved: "Workflow saved successfully"
  settings_saved: "Settings saved successfully"

# Confirmation dialogs
confirmations:
  delete_task: "Are you sure you want to delete this task?"
  delete_workflow: "Are you sure you want to delete this workflow?"
  unsaved_changes: "You have unsaved changes. Are you sure you want to leave?"
  
# Navigation
navigation:
  dashboard: "Dashboard"
  settings: "Settings"
  workflows: "Workflows"
  analytics: "Analytics"
  help: "Help"
  logout: "Logout"